---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/starkandwayne/concourse-tutorial.git
    branch: develop
- name: hello
  type: git
  source:
    uri: https://github.com/flamexd/ak-concourse.git
    branch: master

jobs:
- name: job-hello-world
  public: true
  plan:
  - get: resource-tutorial
  - task: hello-world
    file: resource-tutorial/tutorials/basic/task-hello-world/task_hello_world.yml
  - get: hello
  - task: hello-kitty
    file: hello/456.yml
